apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapplication
  namespace: openshift-gitops
spec:
  destination:
    namespace: demopipeline
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: .
    repoURL: https://github.com/sumit871996/imageidentificationopenshift
    targetRevision: openshift
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
