apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  namespace: quaytest
spec:
  selector:
    matchLabels:
      app: reactapp
  replicas: 6
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: imageidentificationcon
          image: quay-registry-quay-openshift-operators.apps.hpeopenshift.eastus.aroapp.io/quay/imageidentification:0.2.0
          ports:
            - containerPort: 3000
