apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  namespace: quaytest
spec:
  selector:
    matchLabels:
      app: reactapp
  replicas: 5
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: imageidentificationcon
          image: quay.io/sumit-bharat_mandlik/imageidentification:0.1.0
          ports:
            - containerPort: 3000
