kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: imageroutequay1
  namespace: quaytest
  labels:
    app: imageidentification
spec:
  to:
    kind: Service
    name: reactservice
    weight: 100
  port:
    targetPort: 3000-tcp
  wildcardPolicy: None
