kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: imageroutequay
  namespace: quaytest
  labels:
    app: imageidentification
spec:
  host: imageroutequay-quaytest.apps.hpeopenshift.eastus.aroapp.io
  to:
    kind: Service
    name: reactservice
    weight: 100
  port:
    targetPort: 3000-tcp
  wildcardPolicy: None
