apiVersion: v1
kind: Service
metadata:
  name: fastapiservice
spec:
  type: LoadBalancer
  clusterIP: 10.0.89.178
  selector:
    app: fastapiapp
  
  ports:
    - targetPort: 8000
      protocol: TCP
      port: 8000   
