apiVersion: v1
kind: Service
metadata:
  name: reactservice
spec:
  type: LoadBalancer
  clusterIP: 10.0.77.133
  selector:
    app: reactapp
  ports:
    - targetPort: 3000
      protocol: TCP
      port: 3000
